### ISSUE TITLE
Turn on redirection again that will redirect to thank you page

### ISSUE THREAD

**Issue by roaringsheep** [InterviewPrepRepo/IPR_BE#61]

**Comment by roaringsheep** [comment]
full stack feature, need to create thank you page and redirect to there

**Comment by roaringsheep** [comment]
Starting on BE side

**Comment by roaringsheep** [comment]
In IPR-Student, there is thank you component already scaffolded with routing in feature/thankyou branch

**Comment by roaringsheep** [comment]
be branch is feature/redirect-to-thankyou

**Comment by roaringsheep** [comment]
backend done

**Comment by jdelacruz96** [comment]
Done frontend
